<?php

namespace Database\Seeders;

use App\Models\Academic\Subject;
use Illuminate\Database\Seeder;

class SubjectSeeder extends Seeder
{
    public function run(): void
    {
        $subjects = [
            // ========== ISLAMIC CORE SUBJECTS ==========
            [
                'name' => 'Quran',
                'name_arabic' => 'القرآن الكريم',
                'code' => 'QUR',
                'category' => 'islamic',
                'description' => 'Quran recitation, memorization, and understanding',
                'icon' => 'fa-book-quran',
                'color' => '#6B46C1',
                'sort_order' => 1,
                'status' => 'active',
            ],
            [
                'name' => 'Tajweed',
                'name_arabic' => 'التجويد',
                'code' => 'TAJ',
                'category' => 'islamic',
                'description' => 'Rules of Quranic recitation and proper pronunciation',
                'icon' => 'fa-microphone',
                'color' => '#7C3AED',
                'sort_order' => 2,
                'status' => 'active',
            ],
            [
                'name' => 'Hifdh',
                'name_arabic' => 'الحفظ',
                'code' => 'HIF',
                'category' => 'islamic',
                'description' => 'Quran memorization program',
                'icon' => 'fa-brain',
                'color' => '#8B5CF6',
                'sort_order' => 3,
                'status' => 'active',
            ],
            [
                'name' => 'Tafsir',
                'name_arabic' => 'التفسير',
                'code' => 'TAF',
                'category' => 'islamic',
                'description' => 'Exegesis and interpretation of the Holy Quran',
                'icon' => 'fa-book-open',
                'color' => '#6366F1',
                'sort_order' => 4,
                'status' => 'active',
            ],
            [
                'name' => 'Hadith',
                'name_arabic' => 'الحديث الشريف',
                'code' => 'HAD',
                'category' => 'islamic',
                'description' => 'Study of Prophetic traditions and sciences',
                'icon' => 'fa-scroll',
                'color' => '#DC2626',
                'sort_order' => 5,
                'status' => 'active',
            ],
            [
                'name' => 'Fiqh',
                'name_arabic' => 'الفقه',
                'code' => 'FIQ',
                'category' => 'islamic',
                'description' => 'Islamic jurisprudence and legal rulings',
                'icon' => 'fa-gavel',
                'color' => '#D97706',
                'sort_order' => 6,
                'status' => 'active',
            ],
            [
                'name' => 'Aqeedah',
                'name_arabic' => 'العقيدة',
                'code' => 'AQD',
                'category' => 'islamic',
                'description' => 'Islamic creed and theology',
                'icon' => 'fa-star',
                'color' => '#F59E0B',
                'sort_order' => 7,
                'status' => 'active',
            ],
            [
                'name' => 'Tawheed',
                'name_arabic' => 'التوحيد',
                'code' => 'TAW',
                'category' => 'islamic',
                'description' => 'Oneness of Allah and Islamic monotheism',
                'icon' => 'fa-circle',
                'color' => '#10B981',
                'sort_order' => 8,
                'status' => 'active',
            ],
            [
                'name' => 'Seerah',
                'name_arabic' => 'السيرة النبوية',
                'code' => 'SER',
                'category' => 'islamic',
                'description' => 'Biography of Prophet Muhammad ﷺ',
                'icon' => 'fa-history',
                'color' => '#14B8A6',
                'sort_order' => 9,
                'status' => 'active',
            ],
            [
                'name' => 'Islamic History',
                'name_arabic' => 'التاريخ الإسلامي',
                'code' => 'ISH',
                'category' => 'islamic',
                'description' => 'History of Islam and Muslim civilizations',
                'icon' => 'fa-landmark',
                'color' => '#0EA5E9',
                'sort_order' => 10,
                'status' => 'active',
            ],
            [
                'name' => 'Akhlaq',
                'name_arabic' => 'الأخلاق',
                'code' => 'AKH',
                'category' => 'islamic',
                'description' => 'Islamic ethics and character development',
                'icon' => 'fa-heart',
                'color' => '#EC4899',
                'sort_order' => 11,
                'status' => 'active',
            ],
            [
                'name' => 'Adab',
                'name_arabic' => 'الأدب الإسلامي',
                'code' => 'ADA',
                'category' => 'islamic',
                'description' => 'Islamic manners and etiquette',
                'icon' => 'fa-hand-peace',
                'color' => '#F43F5E',
                'sort_order' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Usul al-Fiqh',
                'name_arabic' => 'أصول الفقه',
                'code' => 'USF',
                'category' => 'islamic',
                'description' => 'Principles of Islamic jurisprudence',
                'icon' => 'fa-scale-balanced',
                'color' => '#B45309',
                'sort_order' => 13,
                'status' => 'active',
            ],
            [
                'name' => 'Mustalah al-Hadith',
                'name_arabic' => 'مصطلح الحديث',
                'code' => 'MUH',
                'category' => 'islamic',
                'description' => 'Hadith terminology and classification',
                'icon' => 'fa-tags',
                'color' => '#B91C1C',
                'sort_order' => 14,
                'status' => 'active',
            ],
            
            // ========== ARABIC LANGUAGE SUBJECTS ==========
            [
                'name' => 'Arabic Language',
                'name_arabic' => 'اللغة العربية',
                'code' => 'ARB',
                'category' => 'language',
                'description' => 'Comprehensive Arabic language studies',
                'icon' => 'fa-language',
                'color' => '#0891B2',
                'sort_order' => 20,
                'status' => 'active',
            ],
            [
                'name' => 'Nahw',
                'name_arabic' => 'النحو',
                'code' => 'NAH',
                'category' => 'language',
                'description' => 'Arabic grammar and syntax',
                'icon' => 'fa-diagram-project',
                'color' => '#06B6D4',
                'sort_order' => 21,
                'status' => 'active',
            ],
            [
                'name' => 'Sarf',
                'name_arabic' => 'الصرف',
                'code' => 'SAR',
                'category' => 'language',
                'description' => 'Arabic morphology and word formation',
                'icon' => 'fa-sitemap',
                'color' => '#3B82F6',
                'sort_order' => 22,
                'status' => 'active',
            ],
            [
                'name' => 'Balaghah',
                'name_arabic' => 'البلاغة',
                'code' => 'BAL',
                'category' => 'language',
                'description' => 'Arabic rhetoric and eloquence',
                'icon' => 'fa-feather',
                'color' => '#8B5CF6',
                'sort_order' => 23,
                'status' => 'active',
            ],
            [
                'name' => 'Arabic Literature',
                'name_arabic' => 'الأدب العربي',
                'code' => 'ARL',
                'category' => 'language',
                'description' => 'Classical and modern Arabic literature',
                'icon' => 'fa-book',
                'color' => '#A855F7',
                'sort_order' => 24,
                'status' => 'active',
            ],
            [
                'name' => 'Khat',
                'name_arabic' => 'الخط العربي',
                'code' => 'KHA',
                'category' => 'language',
                'description' => 'Arabic calligraphy',
                'icon' => 'fa-pen-fancy',
                'color' => '#D946EF',
                'sort_order' => 25,
                'status' => 'active',
            ],
            
            // ========== SECULAR SUBJECTS (OPTIONAL) ==========
            [
                'name' => 'Mathematics',
                'code' => 'MATH',
                'category' => 'secular',
                'description' => 'Mathematics for all levels',
                'icon' => 'fa-calculator',
                'color' => '#EF4444',
                'sort_order' => 30,
                'status' => 'active',
            ],
            [
                'name' => 'English Language',
                'code' => 'ENG',
                'category' => 'secular',
                'description' => 'English language and literature',
                'icon' => 'fa-font',
                'color' => '#3B82F6',
                'sort_order' => 31,
                'status' => 'active',
            ],
            [
                'name' => 'Science',
                'code' => 'SCI',
                'category' => 'secular',
                'description' => 'General science including biology, chemistry, physics',
                'icon' => 'fa-flask',
                'color' => '#10B981',
                'sort_order' => 32,
                'status' => 'active',
            ],
            [
                'name' => 'Social Studies',
                'code' => 'SST',
                'category' => 'secular',
                'description' => 'Geography, civics, and social sciences',
                'icon' => 'fa-globe',
                'color' => '#F59E0B',
                'sort_order' => 33,
                'status' => 'active',
            ],
            [
                'name' => 'Computer Studies',
                'code' => 'CMP',
                'category' => 'secular',
                'description' => 'Computer literacy and programming',
                'icon' => 'fa-computer',
                'color' => '#0284C7',
                'sort_order' => 34,
                'status' => 'active',
            ],
        ];
        
        foreach ($subjects as $subject) {
            Subject::updateOrCreate(
                ['code' => $subject['code']],
                $subject
            );
        }
        
        $this->command->info('Subjects seeded successfully!');
    }
}